"""Ensure password_hash column is VARCHAR(256)

Revision ID: bfa670f6bc70
Revises: 7c4eac21e0f1
Create Date: 2024-11-22 13:24:12.105430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfa670f6bc70'
down_revision = '7c4eac21e0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              # Previous column size
                              existing_type=sa.String(length=128),
                              type_=sa.String(length=256),  # New column size
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.String(length=128),
                              type_=mysql.VARCHAR(length=256),
                              nullable=True)

    # ### end Alembic commands ###
